iNESlab/Golbang_BE

- Dockerfile
- docker-compose.yml
- golbang/settings.py
- wait-for-it.sh
Dockerfile과 docke-compose.yml 파일을 작성했습니다. 
> **참고**
- env파일과 기타 코드에 변경사항이 있습니다. 디코 아카이브에 env 코드 전문 올려두었습니다!
> feat: Dockerfile과 docker-compose 등 기타 필요한 파일 추가

- clubs/serializers.py
> hotfix: 클럽 멤버 시리얼라이저에 image url 필드 추가

- clubs/serializers.py
- events/serializers.py
변경 사안 : 이벤트 상세 조회시 club 프로필 정보를 추가하였습니다.
```
{
"status": 200,
"message": "Successfully event list",
"data": [
{
"club": { // 추가됨
"id": 1,
"name": "aa",
"image": null
},
"event_id": 4,
"my_participant_id": 12,
"participants": [
{
"participant_id": 10,
"member": {
"member_id": 3,
"name": "곰곰",
"role": "member",
"profile_image": null
},
"status_type": "PENDING",
"team_type": "NONE",
"hole_number": 15,
"group_type": 1,
"sum_score": 12,
"rank": "0",
"handicap_rank": "0",
"handicap_score": -28
},
{
"participant_id": 11,
"member": {
"member_id": 2,
"name": "문성",
"role": "member",
"profile_image": null
},
"status_type": "PENDING",
"team_type": "NONE",
"hole_number": 6,
"group_type": 1,
"sum_score": 13,
"rank": "0",
"handicap_rank": "0",
"handicap_score": -28
},
{
"participant_id": 12,
"member": { …
```
> Feat: ClubProfile 시리얼라이저 생성 및 Event 상세 조회시 ClubProfile 정보 반환

- accounts/views.py
- docker-compose.yml
- golbang/settings.py
> 1. 아이디/이메일 중복시, 프론트에 어떤 종류의 에러인지 표시가 안돼서 에러를 response에 추가했습니다
> 2. FCM 설정 에러도 수정했습니다. (에러는 아래와 같음)
```
failed to read /Users/yunseongmun/Documents/Golbang_BE/golbang_firebase_sdk.json: line 1: unexpected character "{" in variable name "{"
```
> hotfix: FCM 에러 수정 및 회원가입시 유효성 에러 프론트에 반환

- .github/workflows/main.yml
- Dockerfile.prod
- docker-compose.ci.yml
- docker-compose.moon.yml
- docker-compose.prod.yml
- docker-compose.yml
> Test: CI/CD 기능 구현

- .github/workflows/main.yml
> Config: ci/cd 스크립트 도커 이미지 삭제 sudo로 변경

- golbang/settings.py
>  #55
이전에 보완해야 할 점에 올려둔 내용 보완해서 올립니다
> Hotfix: #55-feat: 설정파일에 FCM 관련 패키지 추가

- .github/workflows/main.yml
- .gitignore
- golbang/settings.py
- golbang/urls.py
- notifications/admin.py
- notifications/apps.py
- notifications/models.py
- notifications/redis_interface.py
- notifications/tests.py
- notifications/urls.py
- notifications/views/notification_views.py
- send_fcm_test.py
- utils/push_fcm_notification.py
>#72
- 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 설명에 커밋 번호도 있다면 도움이 됩니다.
아래 내용 중 수정된 부분 위주로 작성해주세요! (수정되지 않는 부분은 지워주시면 됩니다)
---
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> Hotfix: FCM - serviceAccountKey 재발급 & Feat: 알림 내역 관련 API 추가

- clubs/tasks.py
- events/tasks.py
- notifications/redis_interface.py
- notifications/views/notification_views.py
> #72 
- 
> 급한 이슈 해결한 다음에 다시 PR 내용 채우겠습니다!!
---
- redis에 저장하는 코드가 반복되고 있어서 리팩토링이 필요합니다. 
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> Feat: 알림 조회 API 구현

- accounts/views.py
- clubs/tasks.py
- 
- b21e6f8cfaf67e1062f3644d5e68457a4a148ed0: 모임 생성 후 이벤트 생성할 수 있도록 안내 메시지를 FCM 알림에 추가
- cc6c322bb1edb34eb2891aaaa03c6ec82c9adcdf: User info 수정 함수에 try-except 추가
> Hotfix: 모임 생성 후 안내 메시지 추가 & UserInfo 함수에 try-except 로그 추가 

- clubs/serializers.py
> #76 Product Review 후 수정해야 할 사항 반영
- [모임 메인 - 관리자인 경우 모임이름 밑에 관리자라는 텍스트 추가](https://learntosurf.notion.site/46c898cc1f334ca89720f07fb1d053b1?pvs=4)
- 9b30944f45ef82dd27fafa6f96d441ab3f564040: 모임 조회 시 요청한 사용자가 관리자인지 여부도 함께 반환
> 모임 메인 페이지에서 각 모임에 자신이 관리자인지 아닌지 여부를 텍스트로 남기기 위해 백엔드의 시리얼라이저를 수정하게 되었습니다.
- 관리자인지 아닌지 판단하기 위해 백엔드에서 isAdmin(bool)을 함께 반환하는 것이 좋겠다고 판단했습니다.
그 이유는, 
1. members 목록은 반환되지만 자기 자신이 어떤 member_id인지, 어떤 name인지는 함게 반환되지 않았습니다.
2. 그래서 member_id 또는 name중에서 하나를 반환하여 프론트에서 확인하도록 해야하는데 그렇게 되면 프론트엔드 로직이 복잡해질 것 같다고 판단되었습니다.
3. 그래서 백엔드에서 모임 조회 시 자신이 이 모임의 admin인지 아닌지 여부를 True/False로 담아 반환하기로 했습니다.
---
**해당 부분을 반영하여 API 명세도 수정했으니 꼭 명세 확인해주시길 바라겠습니다!!**
> Feat: 모임 조회 시 요청한 사용자가 관리자인지 여부도 함께 반환

- golf_data/data_import.py
> #76 
- [이벤트 결과 화면 (코스 정보 코드 다시 추가)](https://learntosurf.notion.site/f7a9ca78641042d0a79e16389f26f9bd?pvs=4)
- **문제**: 데이터베이스에 이상한 컬럼(`tee_type`)이 남아 있어서 프로그램이 오류를 냈어요. 또, 데이터에서 이상한 값(예: `~`, `N/D`)이 저장되지 않았음
- **원인**: 컬럼을 모델에서 지웠는데 데이터베이스에는 그대로 남아 있었고, 데이터를 잘못 처리함
- **해결**:
1. 이상한 컬럼을 데이터베이스에서 지웠음
2. 비정상적인 데이터를 `0`으로 바꿔서 안전하게 저장되도록 수정
3. 데이터 저장이 안 되면 새로 만들고, 있으면 업데이트하도록 코드를 고침
- **결과**: 코드 머지된 후 배포된 상태에서 RDB에 잘 저장되는지 확인 필요함
> Hotfix: Golf_course 엑셀파일의 Tees 시트가 제대로 데이터베이스에 저장되지 않는 문제 해결

- participants/models.py
- [홀별 점수에 접근 가능하도록 0을 반환 (백엔드)](https://learntosurf.notion.site/0-37f4a10b2c904ba5ae08ecb72d3a18c7?pvs=4)
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 설명에 커밋 번호도 있다면 도움이 됩니다.
아래 내용 중 수정된 부분 위주로 작성해주세요! (수정되지 않는 부분은 지워주시면 됩니다)
- 214c7ab9f0b181a9320fc778caaf10cf84c41a62:  누락된 홀 점수를 0으로 채워 18홀 점수를 반환하도록 로직 수정
1. **`ScoreCardSerializer`의 `get_scorecard` 메서드 수정**:
- `scorecard` 리스트의 길이를 확인하여 18보다 짧을 경우 누락된 홀을 0으로 채운다.
- 누락된 홀 번호를 기반으로 `scorecard`를 보완하여 반환한다.
```python
def get_scorecard(self, participant):
return participant.get_scorecard() or []
```
그렇다 ScoreSerializer에서 수정해도 4, 5, 6홀과 같이 앞에 순서대로 하지 않을 경우 소용없기 때문에 **Participant Model 내의 get_scorecard 함수를 변경한다.**
메서드가 **{hole_number: score} 형태의 딕셔너리**를 반환해야 한.. 예를 들어:
- 4, 5, 6홀 점수만 입력된 경우: `{4: 4, 5: 5, 6: 6}`
- 반환값을 홀 번호별 …
> Hotfix: 누락된 홀 점수를 0으로 채워 18홀 점수를 반환하도록 로직 수정

- participants/stroke/mysql_interface.py
- participants/stroke/stroke_group_consumers.py
레디스 정보가 mysql에 저장되는지 테스트하기 위한 hotfix 머지입니다.
> hotfix: 참가자 정보 레디스 정보를 읽어올 때, 키값에서 누락된 이벤트 id 추가

- .github/workflows/main.yml
- docker-compose.prod.yml
- participants/stroke/mysql_interface.py
[fix: 스코어 카드 참가자는 참가 수락한 인원들만 반환함](https://github.com/iNESlab/Golbang_BE/pull/94/commits/a08483e54b28c552ee461f8c65c817828adc6da1)
불참 인원도 스코어 카드에 보이는 것을 확인해서, 걸러내는 코드를 추가하였습니다.
[fix: redis 비밀번호 생성(mysql과 동일)](https://github.com/iNESlab/Golbang_BE/commit/0b393e473422d86386f90100136c6cb966bbaad0)
[fix: release용 script생성](https://github.com/iNESlab/Golbang_BE/commit/26b3d7279cdeacaa52a72b01e25fc10bc0e1b877)
> fix&deploy: 스코어 카드 참가자는 참가 수락한 인원들만 반환함+배포용 스크립트 작업

- requirements.txt
- https://github.com/iNESlab/Golbang_BE/pull/94 를 머지한 이후, EC2 서버가 실행 중임에도 앱에서 로그인이 되지 않는 문제가 발생했습니다.
- 로그를 확인한 결과, sympy 패키지를 찾을 수 없다는 에러가 발생했습니다. 이는 해당 PR에서 sympy 패키지의 Q 모듈을 사용하고 있음에도 불구하고, sympy 패키지가 설치되지 않았기 때문이었습니다.
- 이를 해결하기 위해 requirements.txt에 sympy를 추가했습니다.
- [chore: sympy패키지를 requirements 파일에 추가](https://github.com/iNESlab/Golbang_BE/commit/c7baa4f1f355d5a601b3efac18686ded95153779)
- 새로운 패키지를 설치할 경우, 반드시 pip freeze > requirements.txt 명령어를 실행해 requirements.txt 파일을 최신 상태로 업데이트해주시기 바랍니다. 😊
> Hotfix: sympy패키지를 requirements 파일에 추가

- participants/stroke/stroke_event_consumers.py
스코어 카드는 현재 웹소캣연결이 잘되었고, DB에 저장되는 것도 확인되었습니다.
하지만, 랭킹 웹소켓이 지금 문제네요...
이건 코드만으로는 알 수 없어서... error log를 추가하였습니다.
> chore: error log 추가

- participants/routing.py
이전, ALB를 추가하는게 문제가 아니였음.
서버에 설정된 ws를 wss로 표기를 바꿔야함
> hotfix: wss로 업그레이드

- clubs/views/club_admin.py
- 기존의 `api/v1/clubs/#clubId/invite/` API에서 유저를 한명씩 초대하는 로직을   
유저 `리스트`로 받아서 초대할 수 있게 변경하였습니다.
- 또한, 기존 user_id로 프론트 측에서 받는 것은 `user.id`와 `user.user_id`가 헷갈리므로 
프론트 측에서는 `user.user_id`를 받도록 로직을 변경하였습니다.
- response는 `user_id`가 아닌` account_id`로 수정하였습니다.
- `user_id`가 따로 존재하기 때문에, 프론트 측에서는 `user.id`대신, 
`user_id`으로만 받아도 좋을 것 같아요. (user_id가 unique이기도 해서)
- `user.id`를 써야하는 경우, `account_id`로 하는게 어떨까요?
> hotfix: 유저 초대 API를 리스트로 받도록 수정

- Dockerfile.prod
- 서버 마이그레이션 에러를 해결하기 위한 디버깅용 명령어 추가
```
CMD ["/wait-for-it.sh", "redis:6379", "--", "sh", "-c", "\
python manage.py migrate --fake-initial && \
python manage.py makemigrations && \
python manage.py migrate --fake golf_data zero  && \
python manage.py migrate && \
python create-superuser.py && \
python manage.py runserver 0.0.0.0:8000"]
```
---
> Fix(dockerfile): 서버 마이그레이션 에러를 해결하기 위한 디버깅용 명령어 추가

- clubs/views/club_admin.py
[fix(clubs): 모임 수정 시 유저 아이디를 기반으로 처리하는 것이 아닌 ClubMember 아이디를 기반으로 처리하도…](https://github.com/iNESlab/Golbang_BE/commit/d1549ae5d32dcdcd113c340052f8294fc35ced69)
- 기존 모임 수정 API에서는 관리자 역할 업데이트 시 User 모델의 `pk`(유저모델 id)를 기준으로 비교 및 업데이트를 진행했습니다.
- 이번 수정에서는 프론트엔드에서 전달받은 관리자 목록을 `ClubMember`의 `pk`(클럽 멤버 `id`)로 간주하여 처리하도록 변경했습니다.
- 기존의 유저 아이디를 받아 멤버인지 확인한 후 서버에서 모임 멤버 리스트로 바꿔주는 로직이 훨씬 간단해졌으며, 프론트엔드에서도 덜 번거롭게 되었습니다.
- 결과적으로는 모임 수정 시 **클럽 멤버로 등록된 관리자에 한해서만 역할 업데이트가 이루어지며**, 기존 관리자 목록과 비교하여 새롭게 지정된 관리자만 '`admin`'으로 업데이트되고, 목록에서 제외된 클럽 멤버는 '`member`'로 변경됩니다.
>[!TIP]
> 모임 수정 시 `admins` 필드에는 `member id` 목록을 보내주시면 됩니다. (form-data의 경우, 스트링으로)
---
- 테스트코드를 짜면 좋을 것 같습니다.
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
- 현재 테스트는 완료했으나, 해당 방식이 안정적인지는 추가적인 검증이 필요합니다.
> fix(clubs): 모임 수정 시 유저 아이디를 기반으로 처리하는 것이 아닌 ClubMember 아이디를 기반으로 처리하도록 수정

- clubs/views/club_admin.py
refactor: 멤버 초대 응답 수정
- ClubMemberSerializer로 응답
- 프론트에서 memberId가 필요하여 수정하였습니다.
> refactor: 멤버 초대 응답 수정

- clubs/views/club_admin.py
[fix(clubs): bulk_create 후 pk 미반환 문제 해결](https://github.com/iNESlab/Golbang_BE/commit/b121666c56132cb8452fddf6899e18213d5c5b85)
- **문제:**
- 로컬에서는 `invite_member` API를 호출하면, `bulk_create`로 생성된 `ClubMember` 객체에 대해 `pk` 값이 제대로 할당되어 `serializer`가 올바른 데이터를 반환한다.
- 하지만 배포된 서버에서는 `bulk_create` 후 반환된 객체들의 `pk` 값이 채워지지 않아, 이후에 `ClubMember.objects.filter(pk__in=[m.pk for m in created_members])` 쿼리에서 빈 결과가 나오게 되고, 따라서 응답 data가 빈 리스트 `[]`로 나타난다. 
- **원인(추정):**
- 로컬 환경에서는 pk가 반환되지만 배포된 서버에서는 RDS를 사용하므로 pk값이 채워지지 않는 것으로 추정
- **대안:**
- 기존 방식(pk로 조회) 대신 club과 새로 초대할 사용자 ID(`new_users`)를 기준으로 다시 조회한다. (`created_members = ClubMember.objects.filter(club=club, user_id__in=list(new_users)).select_related('user')
`
> [!TIP]
> 동작 과정
> 1. `ClubMember`에 저장:
> 먼저, `new_users`에 해당하는 사용자들에 대해 새 `ClubMember` 객체들을 만들고 …
> fix(clubs): bulk_create 후 pk 미반환 문제 해결

- calculator/admin.py
- calculator/apps.py
- calculator/models.py
- calculator/prompting.py
- calculator/serializers.py
- calculator/templates/calculator/upload_form.html
- calculator/tests.py
- calculator/urls.py
- calculator/views.py
- golbang/settings.py
- golbang/urls.py
- utils/tempfile_helpers.py
> 테스트 레포지토리: https://github.com/iNESlab/new-perio-calc-toy-project
> - 따로 조직 내에 레포지토리를 생성하여 별개의 환경에서 테스트하였습니다. 정상적으로 작동하여 현재 백엔드 코드에 통합하고자 합니다.
> - PR-1: https://github.com/iNESlab/new-perio-calc-toy-project/pull/1
> - PR-2: https://github.com/iNESlab/new-perio-calc-toy-project/pull/2
- 새 앱 생성 및 기본 설정
`Golbang_BE` 프로젝트에 새로운 `calculator` 앱을 생성했습니다.
- [feat: 신페리오 핸디캡 계산 데모를 위한 새로운 앱 생성](https://github.com/iNESlab/Golbang_BE/commit/17a47f8d57904476903591f7a0e6b0915a739b38)
- [feat: calculator 앱의 시리얼라이저, url 매핑 추가, 간단한 테스트용 뷰 추가](https://github.com/iNESlab/Golbang_BE/commit/c0aa7661f5e8521c77608f430e5bc44423cb8b21)
- [feat: calculator URL 매핑 추가](https://github.com/iNESlab/Golbang_BE/commit/e4837a0db1a58b87a6e661dc1e5c28f888a9095b)
- API 로직 연동 및 파일 다운로드 기능
업로드된 엑셀 파일을 처리하여 GPT API를 호출, 신페리오 …
> Feat: 신페리오 핸디캡 계산 기능 및 UI 통합

- calculator/prompting.py
- calculator/serializers.py
- calculator/templates/calculator/upload_form.html
- calculator/views.py
> [!NOTE]
> - 이번 PR에서는 신페리오 계산 로직과 사용자 인터페이스를 개선하여, 사용자가 경기 후 직접 선택한 9홀 정보를 입력받아 신페리오 핸디캡과 점수를 계산하도록 기능을 추가했습니다.
> - 또한, UX 측면에서 동그라미 토글 버튼을 통한 홀 선택 및 제출 버튼 활성화 조건, 성공 메시지 애니메이션 등 여러 개선사항을 반영하였습니다.
- **Before**:
기존에는 단순히 파일 업로드만 받고, 내부에서 추천 홀 정보를 임의로 계산하도록 처리했습니다.
- **After**:
Serializer에 새로운 필드(selected_holes)를 추가하여, 사용자가 쉼표로 구분된 9홀 번호를 직접 입력할 수 있도록 변경했습니다.
- **Before**:
계산 로직이 프롬프트 내에서 무작위로 추천된 홀 정보를 기반으로 신페리오 계산을 수행하고 있었습니다.
- **After**:
프롬프트 메시지에 사용자가 선택한 홀 번호를 포함하도록 수정하고, 골프 코스의 par 데이터 및 전체 타수 정보를 활용하여 신페리오 핸디캡 및 점수를 정확하게 계산하도록 개선했습니다.
(`f"사용자가 선택한 홀 번호는 여기 있습니다.: {selected_holes} (홀은 1~18 홀 사이로 전달해주고 있으니 0-index 처리를 하지 마세요.)"`)
- **Before**:
기존 UI는 단순 텍스트 입력 방식으로 홀 번호를 받거나, 별도의 홀 선택 UI가 없었습니다.
- **After**:
HTML 템플릿에 동그라미 버튼(토글 체크박스) 그룹을 추가하여, 1~18번 홀을 시각적으로 선택할 수 있도록 했습니다.
- 파일 선택 …
> Feat: 추첨 홀 사용자 입력 기반 신페리오 계산 및 UX 개선

- calculator/prompting.py
[feat: 신페리오 최종 점수 계산 방식을 '총 스코어'가 아닌 '총 타수'로 변경](https://github.com/iNESlab/Golbang_BE/commit/b3b56ae6226acda26011f6891723460e40188f93)
**Before:**
- 신페리오 핸디캡 최종 점수는 `{총 타수} - {신페리오 핸디캡}`으로 계산되어야 합니다. (타수 = 특정 홀의 스코어 + 특정 홀의 파)
- 하지만 현재 코드에서는 `{총 스코어} - {신페리오 핸디캡}`으로 계산되고 있었습니다. 
**After:**
- 총 타수를 계산하여 `total_strokes` 리스트에 저장했습니다. (strokes: 타수)
- 신페리오 핸디캡 스코어 계산 시에는 `total_score`가 아닌 `total_strokes`로 계산되도록 수정했습니다.
- 엑셀에 `총 타수` 추가 행을 추가했습니다. 
> [!NOTE] 
> 결과 정상적으로 나오는 점 확인 완료
> <img width="515" alt="스크린샷 2025-03-29 오후 12 57 32" src="https://github.com/user-attachments/assets/b03f7e6b-3607-45b6-afac-60c61ed351c8" />
> feat: 신페리오 최종 점수 계산 방식을 '총 스코어'가 아닌 '총 타수'로 변경

- events/serializers.py
> hotBugTest: 참가자 스코어 기록이 부분적으로 되는 문제

- participants/stroke/redis_interface.py
> hotbug: AsyncResult 버그

- participants/stroke/data_class.py
- participants/tasks.py
- 최초 동기화시에는 적용됨
- 이후, 동기화에서 적용안됨
- 함수명, 로그 변경
> bug: redis -> mysql 동기화시 합계, 랭크 변경 안됨

- participants/tasks.py
- redis에 아직 저장이 안된 참가자가 기존로직에서 동기화 되어 에러 발생
- redis -> mysql 동기화 시간 TODO 추가
이와 별개로 celery-beat에서 에러 로그 확인
```
exc_info=True)\n']
celery-beat  | Traceback (most recent call last):
celery-beat  |   File "/usr/local/lib/python3.12/site-packages/celery/beat.py", line 402, in apply_async
celery-beat  |     return task.apply_async(entry_args, entry_kwargs,
celery-beat  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat  |   File "/usr/local/lib/python3.12/site-packages/celery/app/task.py", line 559, in apply_async
celery-beat  |     check_arguments(*(args or ()), **(kwargs or {}))
celery-beat  | TypeError: calculate_club_ranks_and_points() missing 1 required positional argument: 'club_id'
celery-beat  | 
celery-beat  | During handling of the above exception, another exception …
```
> hotfix: mysql 랭크에 null이 저장되는 버그

- participants/stroke/data_class.py
- 기존에 mysql에 null로 이미 잘못 동기화된 경우를 위해 수정
> hotfix: 기존에 잘못 동기화된 랭크 버그

- golbang/celery.py
- participants/stroke/redis_interface.py
- 로그 추가
- celery 상태 추적 옵션 추가
- PENDING은 동작하지 않는걸로 간주
> bug: celery에 task 로그가 안찍힘

- participants/stroke/stroke_group_consumers.py
[fix: 홀 확인/수정 시 같은 조원에게도 스코어 업데이트 브로드캐스트](https://github.com/iNESlab/Golbang_BE/commit/307269af486fad77e43ddfd32e31aa0740c60b4c) 
- 문제: confirm_hole/uncheck_hole 처리 후 호출자만 즉각 반영되고, 같은 조에 참여한 다른 참여자에게는 즉각 반영되지 않는 문제가 발생
- 해결: group_send과 broadcast_scores 핸들러로 같은 그룹의 모든 참여자에게 send_scores() 전송
- 리팩토링: `input_scores`와 함수명을 `broadcast_scores`로 변경해 역할 명확화
- input_scores 함수를 사용하였으나, input_scores의 함수명은 "스코어 입력"이라는 기능만 의미하는 이름이기에, 스코어 입력, 홀 상태 여부 동기화 모두 아우르는 이름인 broadcast_scores 로 이름을 수정했습니다.
> Fix: 홀 확인/수정 시 같은 조원에게도 스코어 업데이트 브로드캐스트

- accounts/admin.py
[@](https://github.com/iNESlab/Golbang_BE/pull/177) PR 코드 되돌리기
> hotfix: 관리자가 변경하는 코드 제거

- accounts/admin.py
- accounts/forms.py
https://github.com/iNESlab/Golbang_BE/pull/179
> Release: 관리자가 변경하는 코드 제거

- participants/views/participants_view.py
#184 
- async_to_sync 사용
- asyncio.run 제거
> fix: 비동기 무한루프 버그

- golbang/settings.py
- participants/stroke/redis_interface.py
- participants/views/participants_view.py
주의:
- redis에 동기화 키가 있는 상태에서 서버를 ci/cd로 리셋하면, 동기화가 안됨.
- 배포후, redis의 동기화 키들*을 모두 삭제해야함
* 사진 참고
> Deploy: 웹소켓 -> http 변환

- golf_data/data_import.py
- participants/models.py
- participants/routing.py
- participants/stroke/redis_interface.py
fix: 크롤링한 골프장 DB 엑셀 파일 업로드시 발생하는 'nan can not be used with MySQL' 문제 해결
- 크롤링할 때 같이 따라오는 정보라 필요 없는 정보인 TBD로 인한 문제로, TBD 행을 제거하는 구문 추가
- import_excel_data 메서드에 설명 주석 추가
---
> [!NOTE]
> 해당 버그를 해결한 후, 크롤링된 골프장 DB 엑셀 파일이 정상적으로 업로드되어 Database에 저장되는 점 확인했습니다.
> fix: 크롤링한 골프장 DB 엑셀 파일 업로드시 발생하는 'nan can not be used with MySQL' 문제 해결

- participants/models.py
- participants/routing.py
- participants/stroke/redis_interface.py
- 따로 커밋 나눠 한 줄 알았는데 로컬에 있는 수정된 임시 코드가 함께 커밋되어 스테이징 서버가 다운되었습니다.
- 이에 다시 커밋 내역 이전의 코드로 되돌려 문제를 해결했습니다.
> fix: 잘못된 커밋으로 변경된 코드를 다시 되돌리기

- participants/stroke/redis_interface.py
hotfix: release,main에서 누락된 함수명 다시 덮어쓰기
> hotfix: release,main에서 누락된 함수명 다시 덮어쓰기

- participants/stroke/redis_interface.py
Reverts iNESlab/Golbang_BE#199
> Revert "되돌리기"

- participants/stroke/redis_interface.py
- participants/views/participants_view.py
- 기존에는 mysql 호출 시점에서 초기화함
- 더 안전하게 redis 삭제시점에서 mysql 초기화 로직도 추가
> hotfix: 참가자 정보를 삭제할 때, mysql 정보도 초기화

- django/calculator/prompting.py
- django/calculator/templates/calculator/upload_form.html
- django/calculator/views.py
- django/events/serializers.py
- docker-compose.yml
1. GPT 로직 제거 후, 직접 신페리온 계산 => 10초 -> 1초로 단축
2. Par고정값에서 querystring으로 받아오도록 변경
3. EventResult 응답시, Par 정보도 같이 받도록 변경
4. 18홀 삭제되는 로직 변경
> fix: 신페리온 로직 개선

- django/events/serializers.py
- django/events/views/views.py
PATCH  /events/{event_id}/  | 특정 이벤트 종료 ✅
API 만들었습니다.
> feat: 이벤트 종료 API 생성

- django/calculator/templates/calculator/upload_form.html
> refactor: par정보 ui에 띄우기

- django/calculator/views.py
- par정보를 ndarray에서 list로 변환해야함
> hotfix: 신페리온 화면 에러 수정

- django/clubs/models.py
- django/clubs/serializers.py
- django/clubs/views/club_admin.py
- django/clubs/views/club_common.py
- 아직 테스트 못함
- db 테이블 변경 사항 있습니다. (club_member에 status_type 칼럼 추가)
- 최대한 기존 API도 active 유저만 보이도록 수정했는데, 미처 누락된 부분이 있을 수 있습니다..
> Feat: 모임 검색, 지원, 승인 API 생성

- django/clubs/views/club_common.py
- django/utils/push_fcm_notification.py
> Fix: 채팅 알림 및 모임 조회 버그 수정

- django/clubs/views/club_common.py
> hotfix: 빈 모임 목록 조회 시 403 에러 해결

- django/clubs/views/club_common.py
> Hotfix: 모임 조회 부분 상태별 로직 수정
