Dockerfile, auth/jwt_auth_middleware.py, docker-compose.moon.yml, golbang/asgi.py, golbang/settings.py, participants/models.py, participants/routing.py, participants/serializers.py, participants/socket/event_consumers.py, participants/socket/group_consumers.py, requirements.txt
Issue #26 
- jwt 인증 middleware 생성
- 실시간 통신시에는 score 점수가 redis db에 저장된다.
- 조별 스코어 기록/조회 
1. 각 조의 스코어를 기록하고 조회할 수 있다. 
2. 통신 종료시, mysql로 score를 migrate한다.
3. action = get으로 receive 요청시, 점수 갱신이 아닌 같은 조의 전체 스코어를 반환한다.
4. 각 참가자들은 1조부터 정렬해서 반환한다.
- 이벤트 스코어 조회
1. 각 참가자들의 id, profile, last_hole_number, sum_score, handicap_score 들을 반환한다.
2. 어떤 값도 안받아도 receive 요청시, event 참가자 전체 스코어를 반환한다.
3. sum_score를 기준으로 정렬해서 반환한다.
> 참고
0. 유저 프로필 사진 필드가 user entity에 없어서 일단 이미지 url 가져오는 것은 보류했습니다
1. event/group consumers의 메서드가 너무 많아서 util로 빼려했으나 util에서 호출시 인식이 안되는 버그가 있었다.
(gpt 말로는 비동기 함수는 인스턴스나 static으로 해야한다 했는데, static도 안돼서 지금처럼 instance 형태를 유지하였다.)
2. 웹소켓 통신 에러는 기본적으로 http 에러 구현 방식과 많이 달랐다. http 에러처럼 보내려면, 웹소켓 통신이 연결된 후여야 하는데
대부분의 에러는 소켓 통신 연결 전에 발생하는 에러라 이 방법은 시도할 수 없었다. 대신, 로그를 작성하여 프론트에서 에러 발생시 로그를 확인하고 …
=> Feat: 웹소켓 스코어 기록/조회 기능 개발

participants/stroke/data_class.py, participants/stroke/redis_interface.py, participants/stroke/stroke_group_consumers.py
- 웹소켓에서도 스코어 카드 조회시 participant_id만 반환이 돼서 user_name 필드를 추가하였습니다.
- data class post_init 구조도 모든 필드에 대해서 byte 자료형인 경우를 추가하였습니다.
=> Refactor: 소켓 응답시 사용자 이름 추가 및 data class post_init 구조 통일

events/serializers.py
Event의 member_group은
유저 자신이 속한 조를 반환하는 필드인데,
지금까지 null을 반환하는 잘못된 상태였습니다.
그래서, 사진처럼 출력되도록 수정하였습니다
=> Fix: 유저가 속한 조를 반환하지 않던 로직 변경

participants/stroke/redis_interface.py, participants/stroke/stroke_event_consumers.py
> 지금 올리는 커밋은 참가자 sum_score가 0이거나 (미입력된 경우) 랭킹에서 제외하는 로직만 추가한거라
원래라면 이 로직이 없는 경우, 스코어가 0인 친구들도 보여야 하는게 맞는데....
> 
> 데모시연 때는 그것조차 안됐어서 좀 다른 문제인거 같기도 하네요.. 근데 일단 제 로컬에서는
아래 사진처럼 전체현황에서 기능들이 다 동작하기 때문에 올려봅니다
=> Feat: 이벤트 랭킹 조회시 0점 참가자는 제외해서 응답

.gitignore, accounts/forms.py
> #55 
- 16dcb2accbfa1c8057da5899ebeb1df056feef3b: 회원가입 2단계 시, fcm_token을 요청받도록 시리얼라이저에 추가했습니다.
- 129a894166deb37665caaf619c871e45381922cc: fcm에서 사용하는 serviceAccouintKey를 .gitignore에 추가했습니다. 이 serviceAccountKey는 디코 아카이브에 올려두겠습니다!
=> Hotfix: 회원가입 2단계 시리얼라이저에 fcm_token 추가

accounts/serializers.py, docker-compose.yml, golbang/settings.py
- Frontend 단에서 FCM 적용을 위해 몇 가지를 수정하였습니다.
- 시리얼라이저가 fcm_token 포함하도록 수정
- Firebase sdk 임시 키파일 생성 및 디스코드에 게시 (golbang_firebase_sdk.json)
- docker-compose 파일에서 golbang_firebase_sdk.json 파일을 env_file로 포함하도록 추정
- https://learntosurf.notion.site/1018-FCM-53dd77a247404dd089b005b78818a324?pvs=4
- golbang_firebase_sdk.json
=> Hotfix: UserInfo 시리얼라이저 fcm_token 포함으로 수정 및 FCM key파일 적용(임시 키파일 디코에 올림)

.gitignore, accounts/forms.py, accounts/serializers.py, auth/api.py
> #55
- [1018 회의록 - FCM 관련](https://learntosurf.notion.site/1018-FCM-53dd77a247404dd089b005b78818a324?pvs=4)
- 회원가입 및 사용자 조회 시 fcm_token을 받아오거나 보내주는 시리얼라이저에서 fcm_token 제거
- 로그인 시 FCM 토큰을 처리하는 방식으로 변경함
- **FCM 토큰이 없는 경우**: 로그인 시 FCM 토큰이 비어 있다면 새로 발급받아서 사용자 정보에 저장한다.
- **FCM 토큰이 다른 경우**: 만약 로그인할 때 받아온 FCM 토큰이 기존의 토큰과 다르다면, 새로운 토큰으로 업데이트한다. 
- 이전에 중범선배가 올려주신 `golbang_firebase_sdk.json`을 추가해두었습니다.
=> Hotfix: 로그인 시 fcm_token을 

Dockerfile, Dockerfile.prod, accounts/models.py, create-superuser.py, golbang/settings.py
혹시, DB가 초기화 될 경우, 관리자 계정을 새로 만드는 것이 번거롭기 때문에, 
컨테이너 실행시 관리자 계정을 자동으로 만드는 스크립트를 구현했습니다.
User의 createSuperUser부분이 일반적으로 username, email, password 순서라 해서( GPT의견 )
기존 email, user, password 파라미터 순서를 바꾸었습니다.
EC2 IP로 관리자 페이지 접속시 권한이 없다고 나와서
HOST ALLOWED IP에  EC2 IP추가했습니다.
좀 특이한데, web, db 볼륨을 마운트하면 createsuperuser 스크립트가 안먹히더라구요.
그래서, 로컬에서는 ines 관리자 계정이 안될거에요. 
CI/CD 도커 컴포즈에서는 볼륨을 다른 버그때문에 제외했어서 될겁니다~
환경변수 추가되었습니다.
관리자계정 및 EC2 IP 환경변수 추가했어요
=> Feat: 관리자 계정 자동화 스크립트 추가 및 EC2 IP를 장고 호스트 허용 등록

.github/workflows/main.yml
1. 지금 보니 COPY ..에서 컨테이너 내부에 코드만 복사되는게 아닌 도커 컴포즈 파일도 복사되더라구요.
도커 이그노어를 통해 코드만 복사 가능한지 나중에 찾아봐야될 것 같습니다.
2.  도커 로그인 아이디 비번 따로 깃 시크릿으로 분리해, 스크립트 간소화하기
=> Hotfix: 파이어베이스 환경변수 불러오는 스크립트 추가 및 체크아웃 깃 액션 버전 업그레이드

clubs/tasks.py, docker-compose.yml, events/serializers.py, events/tasks.py, utils/push_fcm_notification.py
> resolved #70 - 이벤트/모임/알림 기능 관련하여 프론트엔드 요청사항 반영
- [FCM 알림 보낼 때 event 또는 club 의 id가 프론트엔드측에서 필요하다. 이를 함께 보내주도록 수정해야 한다.](https://learntosurf.notion.site/FCM-event-club-id-17aa261b9b054ac6b2f9e581fabb049a?pvs=4)
- [이벤트 결과 조회 시, 팀전인 경우 누가 어느 팀인지에 대한 정보도 함께 response로 반환해야 한다. 해당 시리얼라이저를 수정해야 한다.](https://learntosurf.notion.site/response-1e18fcab20864ea4b8d3de4a64f88435?pvs=4)
- [알림 메시지를 멀티라인으로 표시하도록 설정](https://learntosurf.notion.site/6949e52073d4467189f69b3416122ab9?pvs=4)
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 설명에 커밋 번호도 있다면 도움이 됩니다.
> **FCM 알림 기능 관련**
- 17c7e960b61ae68de07dc7281e09fe33ff275c9c: Message 클래스에 따라 data 딕셔너리 문자열 필드를 추가하여 모임/이벤트 id 값 전달 **(자세한 내용은 정리된 노션 참고)**
- 프론트에서 id가 잘 전달되고 있는 것도 확인 완료함 
- d0512c84d4ce7d39f31682bf974bbfe66ee61eef: 알림 메시지 멀티라인을 위해 …
=> Feat: 이벤트/모임/알림 기능 관련하여 프론트엔드 요청사항 반영

clubs/tasks.py, events/tasks.py, golbang/settings.py, notifications/redis_interface.py
> #85 
- [(백엔드) notification 관련 → 알림내역목록 네비게이션을 위해서 백엔드에서 event_id, club_id 함께 보내줘야 함](https://learntosurf.notion.site/notification-event_id-club_id-3cd342840fc34239a5301eb6152080b0?pvs=4)
> 알림
- a5c8f61de43d3b21f6e9bebd6d38151854c4b099: 알림 데이터를 redis에 저장하는 기간을 2일에서 7일로 늘림
- a52b2b7820fce39f90b80ffccea948dee2bd0002: 알림 내역을 redis에 저장할 때 event_id 또는 club_id를 함께 저장하도록 하여 알림 내역 반환 시 함께 반환되도록 설정
알림 내역 조회 시 아래와 같이 event_id와 club_id를 반환함. 
```json
{
"status": 200,
"message": "Successfully retrieved notification list",
"data": [
{
"title": "notification test 모임에 초대되었습니다.",
"body": "notification test 달력을 눌러 새로운 일정을 만들어보세요!",
"status": "success",
"timestamp": "2024-12-15T14:31:15.544570",
"read": false,
"notification_id": "f7a3e781-1c1c-420d-8402-a720bc0056d6",
"event_id": …
```
=> Feat: 알림 내역 저장 시간 연장, 알림 저장 시 event_id, club_id 함께 저장, celery beat 작업 수정

clubs/views/club_member.py
- 프론트에서 interceptor로 모임 나가기 api 리팩토링 도중, 서버 500 에러 발생. 
- 로그 분석 후, http 리스폰스 리턴이 안됨을 확인
- 누락된 return 추가
=> hotfix: 모임 나가기 api return 누락 추가

participants/stroke/stroke_event_consumers.py
프론트 작업도중, 게임 랭킹 페이지에서 유저 프로필이 안뜨는 것을 확인.
이전에, s3연결 전, 유저 이미지 연결을 위해 TODO로 주석 처리한 부분을 마저 구현
=> fix: 랭킹 웹소켓에서 유저 프로필 이미지 반환하도록 추가

participants/stroke/stroke_event_consumers.py
프론트에서 게임 랭킹 조회중 서버에서 응답이 안와 로그를 보니 아래 로그를 확인함.
그에 따라 수정
```
response_data: {'event': {'group_win_team': None, 'group_win_team_handicap': None, 'total_win_team': None, 'total_win_team_handicap': None}, 'rankings': [{'user': {'name': 'Jungbeom0', 'profile_image': <ImageFieldFile: accounts/1000000019_rnJJiEL.jpg>}, 'participant_id': 239, 'last_hole_number': 2, 'last_score': 10, 'rank': '1', 'handicap_rank': '1', 'sum_score': 9, 'handicap_score': -91}]}
Sending JSON: {'event': {'group_win_team': None, 'group_win_team_handicap': None, 'total_win_team': None, 'total_win_team_handicap': None}, 'rankings': [{'user': {'name': 'Jungbeom0', 'profile_image': <ImageFieldFile: accounts/1000000019_rnJJiEL.jpg>}, 'participant_id': 239, 'last_hole_number': 2, 'last_score': 10, 'rank': '1', …
```
=> hotfix: 모델 Image타입은 json 직렬이 안됨. url을 추출해서 넣어야함

docker-compose.ci.yml, docker-compose.prod.yml, docker-compose.yml, golbang/settings.py
1. 웹소켓 돋작 안함
2. celery, celery-beat 모두 동작 안함
- 원인
단순히 레디스에 비밀번호를 추가하는 작업이라 생각해 따로 로컬에서 테스트를 안했는데...
이 비밀번호 추가로 레디스와 서버, celery가 모두 연결이 끊겼더라구요.
앞으로 주의하도록 하겠습니다 ㅎㅎ..
- 해결
프론트 테스트는 아직 안했는데, 테스트 서버에 배포되면 진행할 예정입니다.
장고 세팅 파일에 레디스 비밀번호를 추가해주었습니다.
저희 장고는 설정파일이 `.env` 파일에서 직접 가져다 쓰는 형태라
docker-compose 파일의 환경변수를 안쓰고 있더라구요. 그래서, 안쓰는 삭제하였씁니다
=> hotfix: celery에 레디스 비밀번호 환경변수 추가

docker-compose.ci.yml
CI 스크립트에서는 볼륨 설정을 안해서 제거해야하는데, 
복사 과정에서 redis 볼륨이 추가되어 다시 삭제 하였습니다
=> fix: ci에서 볼륨 제거

participants/stroke/redis_interface.py
celery가 꺼지던 문제는 해결됐으나
웹소켓 통신이 안되는 문제는 여전하여 RediInterface에서 사용하는 redis_client에 비밀번호를 추가하였습니다.
=> hotfix: redis_client에 password 추가

golbang/settings.py
```
Exception inside application: RedisChannelLayer.__init__() got an unexpected keyword argument 'password'
```
에러 메시지에서 password를 인자로 넣지 말라 돼있어서, url에 입력하는 형태로 바꾸었습니다.
=> hotfix: CHANNEL_LAYER에 레디스 비밀번호 입력 방식 변경

participants/stroke/mysql_interface.py
이 코드를 추가했던 이유가 스코어카드나 랭킹 페이지에서 불참자들 안보이게 하려고 한건데,
막상 웹소켓 코드를 보니 점수 입력 전까지는 참가자들 명단은 프론트에서 관리하더라구요.
오히려 이게 에러 원인인거 같기도 하고, 불필요해져서 되돌렸습니다.
=> fix: 참가자 상태 무관하게 모두 반환하도록 변경

.github/workflows/main.yml
Release 전용 러널 라벨명을 설정했습니다.
기존에 `self-hosted`에서 `release`로 명시했습니다.
=> Hotfix: release 전용 러너 label 설정

.github/workflows/main.yml, .gitignore
- 현재 테스트 중인 사항으로, `Hotfix`로 PR을 올립니다.
- `build` 작업에서는 브랜치에 따라 다른 env가 설정됩니다.
- 차이점: 
- `main` 브랜치: staging 서버 IP
- `release` 브랜치: production 서버 IP
- `deploy-dev`작업에서는 staging 서버 IP가, `deploy-release` 작업에서는 production 서버 IP가 각각 설정됩니다.
=> Hotfix: CICD 파이프라인에 release 관련 코드 추가

.github/workflows/main.yml
PROD 환경을 위한 **S3와 RDS**를 생성하고, 이를 기반으로 새로운 환경 설정을 업데이트하였습니다.
RDS 생성 시 서브넷이 `1c`에만 생성되어 있어 추가로 `1a`까지 설정을 완료하였습니다. (`1a`와 `1c` 모두 설정되어야만  RDS가 생성된다고 명시되어 있어 추가했습니다.) 또한, Private 서브넷이 라우팅 테이블과 별도로 연결되어 있어야 했으나 해당 설정이 누락되어 있음을 발견하고, 관련 내용을 참고하여 수정하였습니다.
- 참고 사이트:
- [[왕초보 탈출 AWS 매뉴얼(1)] VPC & Public Subnet 생성](https://minjii-ya.tistory.com/32)
- [[왕초보 탈출 AWS 매뉴얼(2)] Private Subnet 생성](https://minjii-ya.tistory.com/33?category=946161)
- `main.yaml`에는 브랜치에 따라 깃허브 시크릿을 가져오는 부분만 다르게 설정하였으며, 필요한 깃허브 시크릿을 새로 추가하였습니다.
- 현재 `deploy-dev`와 `deploy-release`에는 반복되는 코드가 존재하며, 추후 코드 최적화가 필요할 것으로 보입니다.- 
- `env.stag`와 `env.prod`는 디코 아카이브에 새로 업데이트하였으니 참고 부탁드립니다.
=> Hotfix: PROD 용 S3와 RDS 생성 후 github secret 변수명 변경 적용

.github/workflows/main.yml
PROD 환경을 위한 **S3와 RDS**를 생성하고, 이를 기반으로 새로운 환경 설정을 업데이트하였습니다.
RDS 생성 시 서브넷이 `1c`에만 생성되어 있어 추가로 `1a`까지 설정을 완료하였습니다. (`1a`와 `1c` 모두 설정되어야만  RDS가 생성된다고 명시되어 있어 추가했습니다.) 또한, Private 서브넷이 라우팅 테이블과 별도로 연결되어 있어야 했으나 해당 설정이 누락되어 있음을 발견하고, 관련 내용을 참고하여 수정하였습니다.
- 참고 사이트:
- [[왕초보 탈출 AWS 매뉴얼(1)] VPC & Public Subnet 생성](https://minjii-ya.tistory.com/32)
- [[왕초보 탈출 AWS 매뉴얼(2)] Private Subnet 생성](https://minjii-ya.tistory.com/33?category=946161)
- `main.yaml`에는 브랜치에 따라 깃허브 시크릿을 가져오는 부분만 다르게 설정하였으며, 필요한 깃허브 시크릿을 새로 추가하였습니다.
- 현재 `deploy-dev`와 `deploy-release`에는 반복되는 코드가 존재하며, 추후 코드 최적화가 필요할 것으로 보입니다.- 
- `env.stag`와 `env.prod`는 디코 아카이브에 새로 업데이트하였으니 참고 부탁드립니다.
=> Hotfix: PROD 용 S3와 RDS 생성 후 github secret 변수명 변경 적용 -> RELEASE 통합

golbang/settings.py
**변경 사항**
- CSRF 설정 업데이트
- CORS 설정 수정
- CORS_ORIGIN_ALLOW_ALL을 False로 설정
- CORS_ORIGIN_WHITELIST에 도메인 추가
**변경 이유**
현재 Django 백엔드와 Flutter 프론트엔드 간의 통신 시 CSRF 검증 실패 에러가 발생하고 있었습니다. 이는 prod용 도메인이 Django의 `CSRF_TRUSTED_ORIGINS`에 포함되지 않아 발생한 문제라고 판단했습니다.
=> feat: CSRF 오류 해결 및 CORS 화이트리스트 도메인 추가

golbang/settings.py
실제 배포환경에서는 ALB나 NGINX를 이용해서
외부 https를 Http로 바꿔주는게 좋다고 하네용..
그래서, 장고는 http만 쓰면 된다네요
=> hotfix: http -> https 리다이렉트 해제

golbang/settings.py
GPT가 `ALB가 리다이렉트 후 사용하는 도메인` 추가해야한다 해서 추가합니다
=> fix: CSRF 리다이렉트된 경우 추가

golbang/settings.py
```
ec2-user@ip-10-0-1-27 ~]$ docker logs --tail 100 web
File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
response = await get_response(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 235, in _get_response_async
callback, callback_args, callback_kwargs = self.resolve_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 313, in resolve_request
resolver_match = resolver.resolve(request.path_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 702, in resolve
raise Resolver404({"tried": tried, "path": new_path}) …
```
=> hotfix: 웹소켓 통신시, Allowed 에러발생하여 ALB 도메인 추가

golbang/settings.py, participants/routing.py
[fix: 웹소켓 통신시, Allowed 에러발생하여 ALB 도메인 추가](https://github.com/iNESlab/Golbang_BE/commit/99bbd9035b5a06800d237b5d3ab173d863617f64)
이건 알고보니 사실 안해도 되는 작업이더라구요. 그래도 혹시 모르니 그대로 두겠습니다. (ALB 도메인이 쓰일 때가 올수도...)
이제 ws에서 보안을 강화한 wss프로토콜 동작합니다
- https는 aws ALB를 통해 해결
- wss는 https가 되면, 서버에서 경로만 수정하는 것으로 해결됩니다.
1. 프론트에서 https, 8000포트로 요청
2. ALB가 https를 http로 변환하여 EC2 8000포트에 전달
3. 서버는 http로 응답받고 다시 ALB에 http로 응답
4. ALB는 https로 프론트에 응답
> 구글에서 나오는 것들은 http -> https로 바꿔주는 내용에만 치중돼있어서...
서버 포트 이런걸 고려 안하니 나중에 보시게 되면 참고 하십쇼오오
기타) 프론트에서 http, 80포트로 요청시 https, 8000포트로 리아디이렉트 되게끔 설정하였습니다
=> Release: wss 업그레이드 배포

notifications/redis_interface.py
알림이 오는데, 알림 페이지에 안뜨는 문제 발생
원인 : 이전에, redis 비밀번호를 추가하면서 스코어 카드 redis client는 비밀번호를 받도록 수정하였는데,
알림은 조치를 하지 않았음.
수정 : redis client 수정
```
redis_client = redis.StrictRedis(
host='redis', 
port=6379, 
db=0, 
password=settings.REDIS_PASSWORD
)
```
=> hotfix: 알림 redis client에도 redis 비밀번호 전달

clubs/serializers.py
초대시, 기존 회원을 여부를 확인하기 위해, 회원 조회 API에 유저 id추가하기
기존에, ClubMemberSerializer에서
name, profile_image 등 User정보를 이미 쓰고 있어서, 
UserSerializer로 통합해서 사용함
지금, Club쪽에서 안쓰는 시리얼라이즈도 많이 있고,
UserSerializer가 생성돼있는데, UserSerializer를 안사용하고 user로 모든 필드를 가져오는 시리얼라이저들이 보입니다.
이런 부분은 UserSerializer로 간소화하면 좋을 것 같아요.
추가로, API 응답할 때, 
예전에 컨벤션으로 클럽 id면 club_id, 회원이면 member_id
이렇게 약속했던거 같은데, id만 존재하는 경우도 보입니다.
ex) club 조회 API에서 club_id가 그냥 id로 응답되고 있어요.
(user_id는 쩔수지만...)
이런 response에 대한 통일을 리팩토링때 다시 이야기 나누고 진행해야될 것 같습니다.
프론트 리팩토링은 그 후..?
=> hotfix: ClubMember 시리얼라이저 User 필드 추가

accounts/views.py, clubs/views/club_common.py, golf_data/admin.py, utils/compress_image.py, utils/delete_s3_image.py
- Django에서 이미지 압축 및 WebP 변환 적용하기 (🔥 최적화)
> **1. 이미지 압축 및 WebP 변환 함수 생성**
🔗 [feat(utils):업로드된 이미지를 압축하고 WebP 형식으로 변환하는 함수 생성](https://github.com/iNESlab/Golbang_BE/commit/d0b55ee371194b41518fe35de5561b6d593e3cbd)
- 📍 파일 위치: `utils/compress_image.py`
- 업로드된 이미지를 **`70%`** 압축하여 **`WebP`** 형식으로 변환 (PNG, JPG → WebP)
- 투명 배경 유지 가능 (RGBA 지원)
- Pillow 10.0+ 호환 (`Image.Resampling.LANCZOS` 사용)
> **모임 생성 및 사용자 정보 수정 시 이미지 압축 적용**
🔗[feat: 이미지를 업로드하는 모임 생성, 사용자 정보 수정 view 함수에 compress_image 함수를 적용하여 이미…](https://github.com/iNESlab/Golbang_BE/commit/65324f405d864a626c00523b6f899c0695fa4441)
- 📍 적용한 파일 및 함수: 
- `clubs/views/club_common.py` → 모임 생성 시 `compress_image` 적용
- `accounts/views.py` → 사용자 프로필 이미지 수정 시 `compress_image` 적용  
- 변경 내용:  
- `request.FILES.get('image')` 또는 …
=> Feat: 이미지 업로드 최적화 - WebP 변환 및 용량 압축 적용

events/views/views.py
[feat(event): 이벤트 스코어 카드 조회 시 참석/참석회식 을 선택한 참여자들만 반환되도록 필터링 추가](https://github.com/iNESlab/Golbang_BE/commit/008794c609c39b771640d80d7c48990d379cb2ef)
- status_type을 DENY나 PENDING으로 한 경우에도 스코어 카드 결과 조회에 함께 나오고 있습니다.
- 스코어카드에는 ACCEPT나 PARTY로 표시한 참가자들만 보여야 하기 때문에 이를 필터링하는 코드를 추가하였습니다.
```python
group_participants = Participant.objects.filter(
event=event,
group_type=group_type,
status_type__in=[Participant.StatusType.ACCEPT, Participant.StatusType.PARTY] # 여기
)
```
- 해당 기능이 반영된 후 iOS, Android에서 테스트가 필요합니다.
=> feat(event): 이벤트 스코어 카드 조회 시 참석/참석회식 을 선택한 참여자들만 반환되도록 필터링 추가

events/serializers.py, events/tasks.py
- **기존 방식**: 
이벤트 수정 시 기존의 모든 참가자 데이터를 삭제한 후, 새 데이터를 생성하는 방식으로 구현되어 있음
- **문제점**: 
이미 사용자가 변경한 참석 상태(예: ACCEPT, PARTY 등)가 모두 기본값(PENDING)으로 초기화됨
- **개선 이유**:  
삭제 후 재생성하는 방식 보다는 기존 데이터를 비교하고 수정하는 방식이 사용자 경험 및 성능 면에서 유리하기 때문에 이와 같이 진행
- **비교 (from chatGPT)**
|비교 항목 | 새로 생성 (전체 삭제 후 재생성) | 기존 업데이트 (부분 수정) |
|-- | -- | --|
데이터 상태 유지 | 기존 참가자의 상태가 모두 기본값(PENDING)으로 초기화됨(사용자가 변경한 상태가 모두 사라짐)🔴 | 이미 변경된 상태(예: ACCEPT, PARTY 등)가 유지됨(사용자 설정 보존)🟢
코드 복잡성 | 구현이 간단 (모든 참가자를 삭제하고 새 데이터를 생성하는 단순 로직) 🟢 | 기존 데이터를 비교하고 업데이트하는 로직 필요(조금 더 복잡하지만 세밀한 제어 가능)🔴
데이터베이스 부하 | 삭제와 재생성 작업으로 인한 DB 부하 증가🔴 | 변경된 항목만 업데이트하여 불필요한 삭제/생성 작업을 줄임🟢
트랜잭션 안정성 | 대량 삭제 후 재생성 시 트랜잭션 실패 위험 증가 가능🔴 | 필요한 부분만 수정하므로 트랜잭션 안정성이 높음🟢
이력 및 로그 관리 | 기존 데이터가 삭제되어 변경 이력이나 로그 추적이 어려움🔴 | 기존 데이터의 수정 이력이 유지되어 이력 관리가 용이함🟢
사용자 경험 | 참가자의 참석 상태가 모두 초기화되어, …
=> Fix(Event): 이벤트 수정 시 참여자 업데이트 로직 개선(기존 참여자 데이터 부분 업데이트)

clubs/urls.py, clubs/views/club_admin.py, clubs/views/club_member.py
- 모임 수정 API가 프론트엔드 **사용자 피드백**에 따라 확장되었습니다.
- 기존에 단순히 모임의 기본 정보(이름, 설명 등)만 수정하는 것이 아니라, **이미지 수정과 관리자 추가/수정/삭제 기능**도 함께 제공하도록 보완했습니다.
- 이미지 수정 시, 모임 생성 시와 동일하게 form-data로 처리되며, 이미지 압축 기능(`compress_image` 함수)도 적용됩니다.
- 관리자는 사용자 아이디를 리스트로 전달받고, 해당 아이디를 실제 User 모델의 `id`와 `ClubMember`의 `club_member_id`로 대체한 후, 기존 클럽 멤버 중 관리자인 멤버와 비교하여 역할을 업데이트합니다.
1. 입력값 처리 (`process_request_data` 함수)
2. user 객체 조회 - `user` 모델에서 기본키(id)를 얻어 실제 유저인지 조회하고 `admins` 값 대체
3. 역할 업데이트
- 이미 등록된 관리자(`ClubMember`의 role이 `admin`인 사용자)의 Id 목록과 2번 과정을 거친 id 목록 비교
- 새로 추가된 관리자는 role을 `admin`으로 변경
- 기존 관리자 중 새 관리자 리스트에 포함되지 않은 사용자는 role을 `member`로 변경
- ASAP으로 진행되어, 관리자 전용 기능을 별도의 엔드포인트(`admin`)로 분리했습니다.
- 이 변경 없이 진행할 경우, 모임 공통 기능 뷰와 엔드포인트가 충돌하여 PATCH 함수가 제대로 적용되지 않았습니다.
- 앞으로 장기적으로 더 나은 방안을 마련할 예정입니다. 
- 불필요한 import 문은 …
=> Feat(Club): 모임 관리자의 모임 수정 API 기능 보완(엔드포인트 변경/이미지 변경 기능&관리자 변경 기능 추가)

clubs/views/club_admin.py
[fix(clubs): 모임 멤버 강제 삭제 시 User pk가 아닌 Clubmember pk로 처리되도록 수정](https://github.com/iNESlab/Golbang_BE/commit/e2bcb294a7333cd3be46907fd0835ae0d5787e63)
- 모임 멤버 강퇴 시 User pk를 받아오도록 처리되고 있었습니다. 이를 ClubMember pk로 수정했습니다.
- FE에서도 이렇게 처리하고 있는지 확인이 필요합니다.
=> fix(clubs): 모임 멤버 강제 삭제 시 User pk가 아닌 Clubmember pk로 처리되도록 수정

clubs/views/club_admin.py, golf_data/views.py, participants/utils/statistics.py, participants/views/statistics_view.py
[fix(statistics): Response가 이중으로 감싸지는 문제 해결](https://github.com/iNESlab/Golbang_BE/commit/f8aa98c8eb59d4ffb46597d10e7f5e5b59de8760) 
- **문제**
모임 생성 후 서버에서 반복적으로 `500 Internal Server Error`가 발생했습니다.
(로그: Internal Server Error: /api/v1/participants/statistics/overall/)
- **원인**
`calculate_statistics()` 함수가 상황에 따라 `Response` 객체를 직접 반환하면서 `Response(Response(...)) `형태가 되어 에러가 발생했습니다.
이는 함수가 데이터를 반환하거나 `Response` 객체를 반환하는 비일관적인 설계에서 비롯된 문제입니다.
- **해결을 위해 고려한 방식 비교**
기준 | ① `isinstance(data, Response)`로 감지하여 분기 처리 | ② `calculate_statistics()`를 순수 데이터 반환 함수로 리팩토링
-- | -- | --
역할 분리 | 함수 내부에 Presentation 로직 포함 → 단일 책임 원칙 위배 | 함수는 계산만, 응답은 View에서 처리 (SRP 준수)
가독성 | 호출부에서 조건문 추가 필요 | 호출부 로직이 직관적 (if error: return handle_404...)
테스트 용이성 | Response 객체를 목업하거나 파싱 필요 | 데이터 구조만 테스트하면 됨 (심플)
확장성 | 다른 컴포넌트에서 …
=> Bugfix: 중첩 Response 반환 문제 수정 및 통계 계산 로직 분리

events/serializers.py, golbang/settings.py, participants/stroke/data_class.py, participants/stroke/mysql_interface.py, participants/stroke/redis_interface.py, participants/stroke/stroke_event_consumers.py, participants/stroke/stroke_group_consumers.py, participants/tasks.py
[feat: redis <-> mysql 동기화](https://github.com/iNESlab/Golbang_BE/commit/069662e392a1da6126fa64d08a413cdce792cc0b) 
-  celery 비동기 설정 활성화
- celery에서 최대 6시간(키의 유효시간)동안 자동 동기화
- 테스트 용도로 30초 간격으로 동기화
- mysql 동기화 로직 이동 및 안쓰는 코드 주석처리
동기화 로그 
[Refactor: redis_client, 참가자 캐싱, 참가자 카운팅](https://github.com/iNESlab/Golbang_BE/commit/cff864e820b9494b1584e6bcba2381289a831fb7) 
- redis_client 옵션 변경(시간 제한, str 변환 응답)
- 처음 조회된 참가자는 mysql에서 읽어서 redis에 저장
- 이후, 모든 수정은 redis에서 진행
- 참가자 수를 카운팅 하여 모두 나가면, redis<->mysql이 동기화되는 로직
2번째 커밋에서 celery 관련 설정파일 변경했습니다. 참고해주세요.
계속 안됐는데 처음에 저 설정을 몰라서 하루 정도 디버깅했는데... 뭘해도 답이 없더라구요
(저게 True면, 웹소켓과 같은 비동기 통신에서 셀러리를 비동기로 호출이 안되는거 같아요)
간신히 저 설정을 알았는데,
혹..시 다른 celery 기능은 저걸 꺼야하는거면 자동 동기화 기능은 사용하지 못할거 같습니다..ㅎ
- [fix: 테스트를 위해 강제 참석하던 로직 …
=> Refactor: 참가자 캐싱 및 자동 동기화 

participants/stroke/data_class.py, participants/stroke/redis_interface.py, participants/stroke/stroke_event_consumers.py, participants/stroke/stroke_group_consumers.py, participants/tasks.py
[feat: redis->mysql 동기화 키 유효기간 자동 갱신](https://github.com/iNESlab/Golbang_BE/commit/63ce0d27205ed700834e43f582726ebcd63e2c53) 
- 일반키 : 웹소켓 접속 참가자 수 관리
- task키 : celery 작업 여부 관리
- 일반키가 삭제되더라도 celery가 작업중인 경우 task키를 통해, celery를 중복 호출하지 않도록 방지.
[hotfix: str -> int 타입 변환](https://github.com/iNESlab/Golbang_BE/commit/7b9a3062845c138c9b87c69e779dfd278be00352) 
- 음수는 .isdigit로 판별 불가능해서 무조건 int를 씌우도록 변경 (대신, try-catch문으로 안전하게 처리)
[hotfix: 음수인 경우에도 int 형변환 되도록 수정](https://github.com/iNESlab/Golbang_BE/commit/e60d171ceca93a767052929863adaea8522c4a31)
[hotfix: 참가자를 못찾는 버그](https://github.com/iNESlab/Golbang_BE/commit/f4e7bf043f7fcc6d458304d181c15c633a9788aa) 
- 전체 랭킹 웹소켓에서는 프론트에서 event_id를 안받음
- 이로 인해, 참가자를 못찾아서, participant_id만으로 키를 찾도록 변경
- 랭킹 조회시, 참가자를 레디스에서 못찾으면 웹소켓 종료시킴(기존 로직에서는 mysql에서 덮어씌워서 …
=> hotfix: 점수 합계 변경이 안되던 버그 및 프론트에 int가 아닌 string으로 보내던 버그 수정

participants/stroke/redis_interface.py
- AsyncResult에러 원인은 잘못된 패키지 임포트
=> hotfix: celery AsyncResult 패키지 임포트 수정

participants/stroke/redis_interface.py
- 지금 로직은 저장을 안하고 task를 종료함. -마지막으로 수정한 내용이 저장이 안될 수 있음.
=> delete: 저장이 안되는 위험성 있는 코드 주석처리

participants/models.py, participants/stroke/redis_interface.py, participants/stroke/stroke_group_consumers.py
**[feat: 스코어카드 조회 시 비어있는 값은 0이 아닌 Null로 반환되도록 수정](https://github.com/iNESlab/Golbang_BE/commit/0a5f1ac56af8294ddf9555fe21d31ae825bf3915)** 
- 골프에서는 0도 유효한 값을 가지고 있기에 명확한 정보 전달을 위하여 Null로 수정
- 해당 코드는 출력용으로 다른 계산 로직에 사용되지 않기에 Null로 인한 문제는 없다고 봐도 됨
**[feat: feat: score가 Null일 경우, redis에서 해당 키 값을 삭제하는 로직 추가](https://github.com/iNESlab/Golbang_BE/commit/3971d9a1af460aecf357f57b531784a4b4fa29f2)** 
- 기존: Null을 받아올 수 없도록 설정되어있었음
- [입력하지 않은 값]을 명확히 하기 위해 프론트엔드에서 Null 값을 전달하기로 함.
- 이에 따라 서버에서도 Null을 받아올 수 있도록 하고, 받아오는 경우 redis에서 제거하도록 설정
> [!NOTE]
> - [x] 스코어 Null 반환 테스트 완료
> - [x] 스코어 Null 요청 시, redis 키 삭제 테스트 완료
[docs: get_scorecard 함수 내 주석 수정](https://github.com/iNESlab/Golbang_BE/commit/816bf2986cabfc0f541b3c8c9fe822c8c154ae85)
=> Feat: 스코어카드 조회 시 빈 값 Null 반환 및 Redis Null 키 삭제 로직 추가

participants/stroke/redis_interface.py, participants/stroke/stroke_group_consumers.py
[feat: 홀 체크용 redis 메서드 (get_hole_checks, set_hole_check) 메서드 추가](https://github.com/iNESlab/Golbang_BE/commit/cc82ed59a24cb39af4bbc7ecceeca977a34b5239) 
- 확인/수정 버튼을 누를 경우 확인 상태를 저장하는 것이 필요하다.
- 이를 위해 redis에 'event:{event_id}:group:{group_type}:hole_checks'패턴으로 값을 저장한다.
- get과 set을 두어 요청 들어왔을 시에는 set으로 저장하고, send_scores로 데이터를 보내줄 때는 get으로 가져온다.
[feat: 그룹별 홀 확인/수정 기능 및 상태 관리 로직 구현](https://github.com/iNESlab/Golbang_BE/commit/be454eaed318a865e6e36cafe98a0c6939926960) 
- 확인/수정 요청에 따라 다른 로직을 수행할 필요가 있었습니다.
- 수정 요청: uncheck_hole, 확인 요창: confirm_hole, 입력: post로 분기처리했습니다.
- 확인/수정 부분에서 홀 상태 여부를 관리합니다.
[refactor: receive() JSON 파싱 오류(400)와 로직 오류(500) 분리 처리](https://github.com/iNESlab/Golbang_BE/commit/07af6f42baee6035549abbec3f139db925a189d8) 
- 에러 디버깅 시 도움이 되기 위해 에러 핸들링 코드를 추가했습니다.
- JSON 파싱 오류와 …
=> Feat: 그룹별 홀 확인/수정 기능 및 Redis 상태 관리 로직 구현

clubs/tasks.py, participants/tasks.py
> #166 
[fix: 30초 간격이 아닌 15분 간격으로 동기화되도록 수정](https://github.com/iNESlab/Golbang_BE/commit/50b03ad8f37f151b4be4a448ff61be8513f9bdc9)
- 인수인계 이슈에 적힌 내용대로 **30초에서 15분 간격**으로 동기화하도록 수정했습니다.
[bugfix: calculate_club_ranks_and_points 함수 인자 optional 처리 & 인자가 없는 경우 전체 모임을 순회하도록 구성](https://github.com/iNESlab/Golbang_BE/pull/173/commits/c79221c4bf15a6096705c842e443969c448c2417)
- **문제**
Celery Beat가 `calculate_club_ranks_and_points` 를 인자 없이 호출하면서 `TypeError: missing 1 required positional argument: 'club_id'` 에러가 발생함.
- **원인**
- 해당 태스크 함수가 `club_id` 를 필수 인자로 선언되어 있어, 기본값 없이 호출 시 인자 검증 단계에서 실패함.
(`def calculate_club_ranks_and_points(club_id):`)
- `settings.py` 의 Celery Beat 스케줄 설정에서 args 없이 해당 태스크를 호출하도록 되어 있었음. 인자가 있는 경우 'args'를 추가해야 한다고 함. 하지만 매일 자정에 한번에 모든 모임을 업데이트하는 것이므로 함수를 수정해야 했음.
```python …
```
=> Fix: Celery동기화 시간 조정 & Celery TypeError 버그픽스

docker-compose.yml, participants/stroke/redis_interface.py, participants/stroke/stroke_event_consumers.py, participants/stroke/stroke_group_consumers.py
- **문제점**: `confirm_hole` 호출 시 요청자만 `sum_score·handicap_score`가 갱신되고, 나머지 조원은 반영되지 않음. 
→ P2, P3, P4도 입력했지만 랭킹에는 반영되지 않음
- **원인**: `update_participant_sum_and_handicap_score_in_redis` 함수가 요청자에 대해서만 호출되도록 변경되어 그룹 전체에 대한 점수 갱신이 누락됨
(로직 분리하면서 발생한 mistake)
- **해결**:
1. `get_group_participants_from_redis`로 조원 전체 목록을 조회
2. `asyncio.gather`로 모든 조원에 대해 `sum_score·handicap_score` 및 `is_group_win`을 일괄 갱신
- **문제**: `sum_score`가 0인 경우에도 유효한 점수임에도 불구하고 랭킹에서 제외됨
→ P1, P2의 sum_score가 0인데 랭킹에 표시되지 않음
- **원인**: s`um_score == 0`인 참가자를 필터링하는 코드 존재
- **해결**:
1. `sum_score == 0`을 제외하지 않도록 필터링 코드 제거
2. `None`인 경우를 0으로 대체해 `TypeError` 방지
3. 점수 입력 여부 판단 기준을 sum_score → last_hole_number로 변경 (→ sum_score가 0이어도 랭킹 반영을 위한 목적)
(이제는 sum_score가 0이어도 랭킹에 나옴)
- 민정 로컬에서 6379가 사용중이라 6380으로 변경
=> Fix: confirm_hole 시 조원 전체 점수 및 랭킹 반영 버그 수정 & sum_score 0인 경우에도 랭킹에 나오도록 개선

accounts/admin.py, accounts/forms.py
- 비밀번호를 임시 발급 받은 후 지문인식 로그인이 되지 않는 문제가 발생했습니다.
- 사용자가 최대한 빨리 로그인이 되도록 해야 하기 때문에 시간이 오래 걸리는 지문인식 디버깅과 비밀번호 변경 탭 추가 대신에 관리자가 일단 직접 바꿔주기로 결정했습니다.
- 이에 따라 관리자 페이지에서 사용자의 비밀번호를 바꿀 수 있도록 설정했습니다.
> [!IMPORTANT]
> **오늘 비밀번호를 변경해드린 후 바로 다시 없앨 예정입니다.**
=> hotfix: 임시비밀번호 발급 후 원하는 비밀번호로 변경하기 위한 대안으로 관리자가 직접 변경할 수 있는 코드 추가 (추후삭제예정)

auth/api.py, clubs/views/club_common.py, events/views/views.py
- **API 명세서**
**[feat(participants/views): 이벤트 참가자 일괄 관리 API 추가](https://github.com/iNESlab/Golbang_BE/commit/0400b842a8c18a27596b00b6ccb82872ae5cbe92)**
- 이벤트 수정이 아니라 상세 페이지에서도 바로 이벤트의 참가자를 추가/삭제할 수 있는 기능이 필요했음.
- 이에 참가자만 추가/삭제, 조 변경할 수 있는 API만 따로 추가함
- API 명세에 추가 완료 & Postman 테스트 완료
- POST `/events/{event_id}/add-participants/` : 이벤트에 참가자 여러 명을 한 번에 추가
- POST `/events/{event_id}/remove-participants/` : 이벤트에서 참가자 여러 명을 한 번에 제거
- PATCH `/events/{event_id}/update-participants/` : 참가자의 `group_type`(조) 정보를 일괄 수정
**[feat: IsClubAdmin 권한 검사 로직 개선](https://github.com/iNESlab/Golbang_BE/commit/bc0c9c5db70edbfec8c73e279e98cc59c76a6f5e)**
- **문제**: EventViewSet의 add-participants 등 커스텀 액션 호출 시 `has_object_permission`에 넘어오는 `obj`가 `Event` 인스턴스로, 기존에 `club=obj`로 처리하던 …
=> feat: 이벤트 참가자 일괄 관리 API 추가 · 권한 검사 로직 개선 · 로그인 검증 세분화
